---
- name: VSCode  ----  Install
  community.general.snap:
    name:
      - code
    state: present
    classic: true

- name: VSCode  ----  Snippets
  ansible.builtin.import_tasks: 10-snippets.yml
