$ANSIBLE_VAULT;1.1;AES256
64303938363334373235333132383362663364663238363931386662623431343464376232383361
3531333130326665313863313636666264306131636663340a316331326364613033346362343135
65313736656462663536333534303336343538633430323535313862376631613330343364336535
6462373662656464640a386438376436316461633536336136303435303536383131313736623133
63306664386662626236626265303738353534653361323730616163616163366165623131353936
62633534303938393263306130326134656666376439643232303462316665336366313834313937
32313336363866633366646132653638396639656232383962656664626366396239623539643066
64316261383965316561623734613030653538613234366235663137353065383034343661336562
61343734633332383636626435616662323536646131663234396132623035343136363561386239
39373562396162633265393931333266633063383261306364633531323835613632366565303539
63353764636330653139623935383262646462653166343632393931616136346161643164633237
63633331343330336433663433383363643638396134653631656638633032343761343231373137
63663133356338353437336164356430366331393434333139336136663265316138616264663234
66336439326630643665333736373137663537623939663562616465663766626265366339386466
30313737613563343462303730376365396237616238353963633564373932343065343834316231
31353164396332323564343134343735616532646539323939366261316461306637643134623236
3961
