---
# see docs/api-docs/docker/portainer.md
services:

  portainer:
    image: portainer/portainer-ce:2.33.3-alpine
    container_name: portainer
    command: --host unix:///var/run/docker.sock --admin-password-file /tmp/portainer_passwords
    restart: "no"
    ports:
      - 9990:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./portainer.passwd:/tmp/portainer_passwords
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9000 || exit 1"
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 10s

volumes:
  portainer_data:
