$ANSIBLE_VAULT;1.1;AES256
61623430653162333839393761393930633631376534653433303834393265383035383761313961
6332393737303235653461333864386163346166613833660a613931346235326530313763613337
64663637653130316365336266343632656534356639646364623838646162393736623538326362
3637326335633034380a653539326264323665353938306133303466633932393535333934633938
38386261636531663366306236653664313064383766336233383432393965363964333332313039
34316235306630616234363438666662386330663233633136613236363739653765366561366433
63303332386534353231666166626333363063306263356433633961323934666530313362366361
31386135663734353362313431663961316639336333653232323632393766343939316430323935
61613361613139353137323063353834353635333963303031313034643932343938633164313739
61643633366239343064373634363466633333356562306261396165663832303662373264636637
38303861313731306561636565643036626232393531663930666635663833306633373264323138
31333839303230363736663735363333346562376161636265363337316433306537343632343432
64656335633230356263323862393836333132333330663363323131636332316532663961313035
62306663323330323032386663663335613134316531666361363263393563653264613232336630
66633164303066313436633364653739663532663062306361353330613430353661376531366331
64353034393564373966
